import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import ExcelJS from 'exceljs';

test('login, painel, compartilhamento, promotor, TI, pendências e offline',async({page,context})=>{
  await mkdir('test-results/visual',{recursive:true});
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Entrar'})).toBeVisible();
  await page.screenshot({path:'test-results/visual/01-login.png'});
  await page.getByLabel('E-mail').fill('e2e@example.invalid');
  await page.getByLabel('Senha').fill('Testing-Password-123');
  await page.getByRole('button',{name:'Entrar'}).click();
  await expect(page.getByRole('heading',{name:'Armários'})).toBeVisible();
  await expect(page.getByText('3 resultados')).toBeVisible();
  await page.screenshot({path:'test-results/visual/02-painel.png'});
  await page.getByRole('button',{name:/102/}).click();
  await expect(page.getByRole('heading',{name:'Principal · Armário 102'})).toBeVisible();
  await expect(page.getByText('Ana Exemplo').last()).toBeVisible();
  await expect(page.getByText('Bia Fictícia').last()).toBeVisible();
  await page.screenshot({path:'test-results/visual/03-compartilhado.png'});
  await page.getByRole('button',{name:'Pessoas'}).click();
  await page.getByRole('heading',{name:'Cadastrar pessoa externa'}).scrollIntoViewIfNeeded();
  await page.getByLabel('Nome',{exact:true}).fill('Promotora Teste');
  await page.getByLabel('Matrícula').fill('0003');
  await page.getByRole('button',{name:'Salvar cadastro'}).click();
  await expect(page.getByText('Promotora Teste').first()).toBeVisible();
  await page.screenshot({path:'test-results/visual/04-promotor.png'});
  await page.getByRole('button',{name:'Importação'}).click();
  await page.getByLabel('Arquivo XLSX ou CSV (até 10 MB)').setInputFiles({name:'ti.csv',mimeType:'text/csv',buffer:Buffer.from('MATRÍCULA;NOME;SETOR;FUNÇÃO\r\n0001;Ana Exemplo;Loja;Operadora\r\n0002;Bia Fictícia;Loja;Operadora\r\n')});
  await page.getByLabel('Delimitador CSV').selectOption(';');
  await page.getByRole('button',{name:'Inspecionar arquivo'}).click();
  await expect(page.getByRole('heading',{name:'Mapeamento e amostra'})).toBeVisible();
  await page.getByRole('button',{name:'Comparar com base atual'}).click();
  await page.getByRole('heading',{name:'Prévia do lote'}).scrollIntoViewIfNeeded();
  await expect(page.getByRole('heading',{name:'Prévia do lote'})).toBeVisible();
  await page.screenshot({path:'test-results/visual/05-previa-ti.png'});
  const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('ARMÁRIOS');
  sheet.addRow(['N°','NOME','MATRÍCULA','STATUS','DUPLO','SETOR','FUNÇÃO']);
  sheet.addRow(['501','','','DISPONÍVEL',false,'','']);
  await page.getByLabel('Arquivo XLSX ou CSV (até 10 MB)').setInputFiles({name:'migracao.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(await workbook.xlsx.writeBuffer())});
  await page.getByRole('button',{name:'Preparar migração do arquivo selecionado'}).click();
  await expect(page.getByRole('heading',{name:'Revisão da migração'})).toBeVisible();
  await page.getByText('Revisar 1 linha de origem, categorias e capacidades').click();
  await expect(page.getByRole('spinbutton',{name:'Capacidade do armário 501'})).toHaveValue('1');
  await page.screenshot({path:'test-results/visual/05b-previa-migracao.png'});
  await page.getByRole('button',{name:'Pendências',exact:true}).click();
  await expect(page.getByText('Promotora Teste')).toBeVisible();
  await page.screenshot({path:'test-results/visual/06-pendencias.png'});
  await page.getByRole('button',{name:'Administração'}).click();
  await page.getByRole('button',{name:'Autorizar este navegador'}).click();
  await expect(page.getByText('Este navegador foi autorizado')).toBeVisible();
  await expect(page.getByRole('button',{name:'Revogar'})).toBeVisible();
  await page.waitForFunction(async()=>{const request=indexedDB.open('armarios-offline',1);return new Promise(resolve=>{request.onsuccess=()=>{const tx=request.result.transaction('state','readonly'),get=tx.objectStore('state').get('copy');get.onsuccess=()=>resolve(!!get.result);};request.onerror=()=>resolve(false);});});
  await page.evaluate(()=>navigator.serviceWorker.ready);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Armários'})).toBeVisible();
  await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByText(/Offline · somente consulta/)).toBeVisible();
  await expect(page.getByText(/Cópia de/)).toBeVisible();
  await page.screenshot({path:'test-results/visual/07-offline.png'});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/visual/08-offline-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Sair'}).click();
  await expect(page.getByRole('heading',{name:'Consulta indisponível'})).toBeVisible();
  expect(await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('armarios-offline',1);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return new Promise(resolve=>{const tx=db.transaction('state','readonly'),request=tx.objectStore('state').get('copy');request.onsuccess=()=>resolve(request.result);});})).toBeUndefined();
  await context.setOffline(false);
  await expect(page.getByRole('heading',{name:'Entrar'})).toBeVisible();
});
