import {useEffect,useState} from 'react';
import {api,op,post,patch} from '../api';
import {saveDevice} from '../offline';
import type {PageProps} from '../App';
import {conditionName,DataState,EmptyState,roleName} from '../ui';
type Locker={id:string;number:string;sector_occupant:string|null;size:string;capacity:number;is_double:boolean;condition:string;modality:string;destination:string|null;version:number;occupants:unknown[];migration_status:string};
type User={id:string;username:string;role:string;active:boolean;must_change_password:boolean;version:number};
type Device={id:string;label:string;revoked_at:string|null;version:number;created_at:string};
export function Admin({branchId,readonly,refresh,notice,general=false}:PageProps&{general?:boolean}){
  const [lockers,setLockers]=useState<Locker[]>([]),[users,setUsers]=useState<User[]>([]),[devices,setDevices]=useState<Device[]>([]);
  const [branchName,setBranchName]=useState(''),[timezone,setTimezone]=useState('America/Fortaleza');
  const [locker,setLocker]=useState({number:'',size:'padrao',capacity:1,isDouble:false,modality:'fixo',destination:'',sectorOccupant:'',condition:'disponivel'});
  const [username,setUsername]=useState(''),[role,setRole]=useState('operador'),[temporaryPassword,setTemporaryPassword]=useState(''),[deviceLabel,setDeviceLabel]=useState('PC da supervisão');
  const [sectorEditor,setSectorEditor]=useState<string|null>(null),[sectorValue,setSectorValue]=useState('');
  const [resetEditor,setResetEditor]=useState<string|null>(null),[resetValue,setResetValue]=useState('');
  const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
  async function load(){if(!branchId){setLoading(false);return;}setLoading(true);setLoadError('');try{const [b,c,d]=await Promise.all([api<Locker[]>(`/branches/${branchId}/lockers`),api<User[]>(`/branches/${branchId}/users`),api<Device[]>(`/branches/${branchId}/devices`)]);setLockers(b);setUsers(c);setDevices(d);}
    catch(e){setLoadError(e instanceof Error?e.message:'Confira a conexão e tente novamente.');throw e;}finally{setLoading(false);}}
  useEffect(()=>{if(!readonly)load().catch(()=>{});},[branchId,readonly]);
  async function act(fn:()=>Promise<unknown>,message:string){try{await fn();try{await load();refresh();notice(message);}catch{notice('A alteração foi concluída, mas a lista não foi atualizada. Recarregue antes de agir novamente.');}return true;}
    catch(e){notice(e instanceof Error?e.message:'Não foi possível concluir a alteração.');return false;}}
  async function createBranch(event:React.FormEvent){event.preventDefault();try{await post('/branches',{operationId:op(),name:branchName,timezone});window.location.reload();}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  async function createLocker(event:React.FormEvent){event.preventDefault();if(await act(()=>post(`/branches/${branchId}/lockers`,{operationId:op(),...locker,destination:locker.destination||null,sectorOccupant:locker.sectorOccupant||null}),`Armário ${locker.number} cadastrado.`))setLocker({...locker,number:'',destination:'',sectorOccupant:''});}
  async function createUser(event:React.FormEvent){event.preventDefault();if(await act(()=>post(`/branches/${branchId}/users`,{operationId:op(),username,role,temporaryPassword}),`Acesso de ${username} criado.`)){setUsername('');setTemporaryPassword('');}}
  async function reset(event:React.FormEvent,user:User){event.preventDefault();if(await act(()=>post(`/branches/${branchId}/users/${user.id}/reset`,{operationId:op(),expectedVersion:user.version,temporaryPassword:resetValue}),`Senha de ${user.username} redefinida. A troca será exigida no próximo acesso.`)){setResetEditor(null);setResetValue('');}}
  async function toggleUser(user:User){if(!window.confirm(`${user.active?'Desativar':'Ativar'} o acesso de ${user.username}?`))return;await act(()=>patch(`/branches/${branchId}/users/${user.id}`,{operationId:op(),expectedVersion:user.version,active:!user.active}),`Acesso de ${user.username} ${user.active?'desativado':'ativado'}.`);}
  async function changeRole(user:User,next:string){if(next===user.role||!window.confirm(`Alterar o perfil de ${user.username} para ${roleName[next]}?`))return;await act(()=>patch(`/branches/${branchId}/users/${user.id}`,{operationId:op(),expectedVersion:user.version,role:next}),`Perfil de ${user.username} atualizado.`);}
  async function toggleDouble(item:Locker){await act(()=>patch(`/branches/${branchId}/lockers/${item.id}`,{operationId:op(),expectedVersion:item.version,isDouble:!item.is_double,capacity:item.is_double?1:2}),`Tipo do armário ${item.number} atualizado.`);}
  async function sector(event:React.FormEvent,item:Locker){event.preventDefault();if(item.sector_occupant&&!sectorValue.trim()&&!window.confirm(`Liberar a ocupação do setor ${item.sector_occupant} no armário ${item.number}?`))return;
    if(await act(()=>patch(`/branches/${branchId}/lockers/${item.id}`,{operationId:op(),expectedVersion:item.version,sectorOccupant:sectorValue.trim()||null}),`Setor ocupante do armário ${item.number} atualizado.`))setSectorEditor(null);}
  async function condition(item:Locker,value:string){if(value===item.condition||!window.confirm(`Alterar a situação do armário ${item.number} para ${conditionName[value]}?`))return;await act(()=>patch(`/branches/${branchId}/lockers/${item.id}`,{operationId:op(),expectedVersion:item.version,condition:value}),`Situação do armário ${item.number} atualizada.`);}
  async function device(event:React.FormEvent){event.preventDefault();try{const result=await post<{secret:string;id:string}>(`/branches/${branchId}/devices`,{operationId:op(),label:deviceLabel});await saveDevice(result.secret);
      try{await load();refresh();notice('Este navegador foi autorizado para consulta offline. A cópia será atualizada.');}catch{notice('O navegador foi autorizado, mas a lista não foi atualizada. Recarregue antes de agir novamente.');}}
    catch(e){notice(e instanceof Error?e.message:'Não foi possível autorizar este navegador.');}}
  async function revokeDevice(item:Device){if(!window.confirm(`Revogar ${item.label}? A consulta offline será apagada ao reconectar.`))return;await act(()=>post(`/branches/${branchId}/devices/${item.id}/revoke`,{operationId:op(),expectedVersion:item.version}),`Autorização de ${item.label} revogada.`);}
  return <div className="stack">{general&&<section className="card"><span className="eyebrow">Estrutura</span><h2>Criar filial</h2><form className="inline-form" onSubmit={createBranch}><label>Nome<input required value={branchName} onChange={e=>setBranchName(e.target.value)}/></label><label>Fuso horário<input required value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><button className="primary">Criar filial</button></form></section>}
    {!branchId?null:readonly?<section className="card"><EmptyState title="Administração indisponível" description="Este perfil ou a consulta sem conexão não permite alterar dados."/></section>:<>
      <DataState loading={loading} error={loadError} onRetry={()=>{load().catch(()=>{});}}/>
      {!loading&&!loadError&&<>
      <section className="card"><span className="eyebrow">Cadastro e capacidade</span><h2>Armários</h2>
        {lockers.length?<div className="table-wrap admin-locker-table"><table><thead><tr><th>Número</th><th>Tipo</th><th>Ocupação</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{lockers.map(x=><tr key={x.id}>
          <td data-label="Número"><strong>{x.number}</strong></td><td data-label="Tipo">{x.is_double?'Duplo · ':''}{x.capacity} {x.capacity===1?'vaga':'vagas'}</td><td data-label="Ocupação">{x.sector_occupant?`Setor: ${x.sector_occupant}`:x.occupants.length?`${x.occupants.length} ${x.occupants.length===1?'pessoa':'pessoas'}`:'Livre'}</td>
          <td data-label="Situação">{conditionName[x.condition]??'Não informada'}{x.migration_status==='inconclusivo'?' · conferência pendente':''}</td><td data-label="Ações"><div className="row-actions"><button onClick={()=>toggleDouble(x)}>{x.is_double?'Remover indicação de duplo':'Marcar duplo'}</button>
            <label className="inline-control">Situação<select aria-label={`Situação do armário ${x.number}`} value={x.condition} onChange={event=>condition(x,event.target.value)}><option value="disponivel">Disponível</option><option value="manutencao">Em manutenção</option><option value="bloqueado">Bloqueado</option></select></label>
            <button onClick={()=>{setSectorEditor(sectorEditor===x.id?null:x.id);setSectorValue(x.sector_occupant??'');}}>Setor ocupante</button></div>
            {sectorEditor===x.id&&<form className="inline-edit" onSubmit={event=>sector(event,x)}><label>Setor que ocupa o armário {x.number}<input value={sectorValue} onChange={event=>setSectorValue(event.target.value)} placeholder="Deixe vazio para liberar"/></label><p>Armários ocupados por pessoas precisam ser liberados antes de atribuir um setor.</p><button className="primary">Salvar setor</button><button type="button" onClick={()=>setSectorEditor(null)}>Cancelar</button></form>}</td></tr>)}</tbody></table></div>:<EmptyState title="Nenhum armário cadastrado" description="Cadastre o primeiro armário abaixo ou use a carga inicial em Importações."/>}
        <h3 className="subsection-title">Novo armário</h3><form className="form-grid" onSubmit={createLocker}><label>Número<input required value={locker.number} onChange={e=>setLocker({...locker,number:e.target.value})}/></label><label className="check"><input type="checkbox" checked={locker.isDouble} onChange={e=>setLocker({...locker,isDouble:e.target.checked,capacity:e.target.checked?2:1})}/>Armário duplo (dois compartimentos)</label><label>Modalidade<select value={locker.modality} onChange={e=>setLocker({...locker,modality:e.target.value})}><option value="fixo">Fixo</option><option value="rotativo">Rotativo</option></select></label><label>Destinação<input value={locker.destination} onChange={e=>setLocker({...locker,destination:e.target.value})}/></label><label>Setor ocupante (opcional)<input value={locker.sectorOccupant} onChange={e=>setLocker({...locker,sectorOccupant:e.target.value})} placeholder="Ex.: Jerinana"/></label><button className="primary">Cadastrar armário</button></form></section>
      <section className="card"><span className="eyebrow">Permissões</span><h2>Acessos</h2><div className="list">{users.map(x=><div className="list-row" key={x.id}><div><strong>{x.username}</strong><small>{roleName[x.role]??'Perfil de acesso'} · {x.active?'ativo':'inativo'}{x.must_change_password?' · troca de senha pendente':''}</small></div><div className="user-actions"><div className="row-actions"><label className="inline-control">Perfil<select aria-label={`Perfil de ${x.username}`} value={x.role} onChange={event=>changeRole(x,event.target.value)}>{x.role==='geral'&&<option value="geral" disabled>Administração geral</option>}<option value="filial_admin">Administração da filial</option><option value="operador">Operação</option><option value="consulta">Consulta</option></select></label><button onClick={()=>toggleUser(x)}>{x.active?'Desativar':'Ativar'}</button><button onClick={()=>{setResetEditor(resetEditor===x.id?null:x.id);setResetValue('');}}>Redefinir senha</button></div>
        {resetEditor===x.id&&<form className="inline-edit" onSubmit={event=>reset(event,x)}><label>Nova senha temporária para {x.username}<input type="password" autoComplete="new-password" required minLength={12} value={resetValue} onChange={event=>setResetValue(event.target.value)}/></label><p>A troca será exigida no próximo acesso.</p><button className="primary">Salvar nova senha</button><button type="button" onClick={()=>setResetEditor(null)}>Cancelar</button></form>}</div></div>)}</div><h3 className="subsection-title">Novo usuário</h3><form className="form-grid" onSubmit={createUser}><label>Nome de usuário<input required minLength={3} pattern="[a-zA-Z0-9._-]+" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Perfil<select value={role} onChange={e=>setRole(e.target.value)}><option value="filial_admin">Administração da filial</option><option value="operador">Operação</option><option value="consulta">Consulta</option></select></label><label>Senha temporária<input type="password" minLength={12} required value={temporaryPassword} onChange={e=>setTemporaryPassword(e.target.value)}/></label><button className="primary">Criar usuário</button></form></section>
      <section className="card"><span className="eyebrow">Continuidade</span><h2>Consulta sem conexão</h2><p>Autorize este navegador no PC da supervisão. A cópia é somente para consulta e expira após 24 horas.</p><form className="inline-form" onSubmit={device}><label>Identificação do dispositivo<input value={deviceLabel} onChange={e=>setDeviceLabel(e.target.value)}/></label><button>Autorizar este navegador</button></form><div className="list">{devices.map(item=><div className="list-row" key={item.id}><div><strong>{item.label}</strong><small>{item.revoked_at?'Revogado':'Autorizado'} · {new Date(item.created_at).toLocaleDateString('pt-BR')}</small></div>{!item.revoked_at&&<button onClick={()=>revokeDevice(item)}>Revogar</button>}</div>)}</div></section>
      </>}
    </>}
  </div>;
}
