import {useEffect,useState} from 'react';
import {api,op,post,patch} from '../api';
import {saveDevice} from '../offline';
import type {PageProps} from '../App';
type Location={id:string;name:string;version:number};
type Locker={id:string;number:string;location_name:string;location_id:string;size:string;capacity:number;condition:string;modality:string;destination:string|null;version:number;occupants:unknown[];migration_status:string};
type User={id:string;email:string;role:string;active:boolean;must_change_password:boolean;version:number};
type Device={id:string;label:string;revoked_at:string|null;version:number;created_at:string};
export function Admin({branchId,readonly,refresh,notice,general=false}:PageProps&{general?:boolean}){
  const [locations,setLocations]=useState<Location[]>([]),[lockers,setLockers]=useState<Locker[]>([]),[users,setUsers]=useState<User[]>([]),[devices,setDevices]=useState<Device[]>([]);
  const [branchName,setBranchName]=useState(''),[timezone,setTimezone]=useState('America/Fortaleza'),[locationName,setLocationName]=useState('');
  const [locker,setLocker]=useState({locationId:'',number:'',size:'padrao',capacity:1,modality:'fixo',destination:'',condition:'disponivel'});
  const [email,setEmail]=useState(''),[role,setRole]=useState('operador'),[temporaryPassword,setTemporaryPassword]=useState(''),[deviceLabel,setDeviceLabel]=useState('PC da supervisão');
  async function load(){if(!branchId)return;const [a,b,c,d]=await Promise.all([api<Location[]>(`/branches/${branchId}/locations`),api<Locker[]>(`/branches/${branchId}/lockers`),api<User[]>(`/branches/${branchId}/users`),api<Device[]>(`/branches/${branchId}/devices`)]);setLocations(a);setLockers(b);setUsers(c);setDevices(d);setLocker(x=>({...x,locationId:x.locationId||a[0]?.id||''}));}
  useEffect(()=>{if(!readonly)load().catch(e=>notice(e.message));},[branchId,readonly]);
  async function act(fn:()=>Promise<unknown>){try{await fn();await load();refresh();notice('Alteração registrada.');}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  async function createBranch(event:React.FormEvent){event.preventDefault();try{await post('/branches',{operationId:op(),name:branchName,timezone});window.location.reload();}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  async function createLocation(event:React.FormEvent){event.preventDefault();await act(()=>post(`/branches/${branchId}/locations`,{operationId:op(),name:locationName}));setLocationName('');}
  async function renameLocation(item:Location){const name=window.prompt(`Novo nome do local ${item.name}:`,item.name);if(!name||name===item.name)return;await act(()=>patch(`/branches/${branchId}/locations/${item.id}`,{operationId:op(),expectedVersion:item.version,name}));}
  async function createLocker(event:React.FormEvent){event.preventDefault();await act(()=>post(`/branches/${branchId}/lockers`,{operationId:op(),...locker,destination:locker.destination||null}));setLocker({...locker,number:'',destination:''});}
  async function createUser(event:React.FormEvent){event.preventDefault();await act(()=>post(`/branches/${branchId}/users`,{operationId:op(),email,role,temporaryPassword}));setEmail('');setTemporaryPassword('');}
  async function reset(user:User){const password=window.prompt(`Nova senha temporária para ${user.email} (12 caracteres ou mais):`);if(!password)return;await act(()=>post(`/branches/${branchId}/users/${user.id}/reset`,{operationId:op(),expectedVersion:user.version,temporaryPassword:password}));}
  async function toggleUser(user:User){if(!window.confirm(`${user.active?'Desativar':'Ativar'} ${user.email}?`))return;await act(()=>patch(`/branches/${branchId}/users/${user.id}`,{operationId:op(),expectedVersion:user.version,active:!user.active}));}
  async function changeRole(user:User){const next=window.prompt('Perfil: filial_admin, operador ou consulta',user.role);if(!next||next===user.role)return;await act(()=>patch(`/branches/${branchId}/users/${user.id}`,{operationId:op(),expectedVersion:user.version,role:next}));}
  async function updateLocker(item:Locker){const value=window.prompt(`Capacidade de ${item.location_name} · ${item.number}:`,String(item.capacity));if(value===null)return;await act(()=>patch(`/branches/${branchId}/lockers/${item.id}`,{operationId:op(),expectedVersion:item.version,capacity:Number(value)}));}
  async function condition(item:Locker){const value=window.prompt('Condição: disponivel, manutencao ou bloqueado',item.condition);if(!value)return;await act(()=>patch(`/branches/${branchId}/lockers/${item.id}`,{operationId:op(),expectedVersion:item.version,condition:value}));}
  async function device(event:React.FormEvent){event.preventDefault();try{const result=await post<{secret:string;id:string}>(`/branches/${branchId}/devices`,{operationId:op(),label:deviceLabel});await saveDevice(result.secret);await load();refresh();notice('Este navegador foi autorizado para consulta offline. A cópia será atualizada.');}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  async function revokeDevice(item:Device){if(!window.confirm(`Revogar ${item.label}? A consulta offline será apagada ao reconectar.`))return;await act(()=>post(`/branches/${branchId}/devices/${item.id}/revoke`,{operationId:op(),expectedVersion:item.version}));}
  return <div className="stack">{general&&<section className="card"><h2>Criar filial</h2><form className="inline-form" onSubmit={createBranch}><label>Nome<input required value={branchName} onChange={e=>setBranchName(e.target.value)}/></label><label>Fuso<input required value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><button className="primary">Criar filial</button></form></section>}
    {!branchId?null:readonly?<section className="card"><p>Administração indisponível neste perfil ou em modo offline.</p></section>:<>
      <section className="card"><h2>Locais</h2><div className="chips">{locations.map(x=><button className="chip" key={x.id} onClick={()=>renameLocation(x)} title="Renomear local">{x.name} · editar</button>)}</div><form className="inline-form" onSubmit={createLocation}><label>Novo local<input required value={locationName} onChange={e=>setLocationName(e.target.value)}/></label><button>Adicionar local</button></form></section>
      <section className="card"><h2>Armários e capacidades</h2><div className="table-wrap"><table><thead><tr><th>Local e número</th><th>Porte</th><th>Capacidade</th><th>Ocupantes</th><th>Condição</th><th>Ações</th></tr></thead><tbody>{lockers.map(x=><tr key={x.id}><td>{x.location_name} · {x.number}</td><td>{x.size==='grande'?'Grande':'Padrão'}</td><td>{x.capacity}</td><td>{x.occupants.length}</td><td>{x.condition}{x.migration_status==='inconclusivo'?' · revisão':''}</td><td><div className="row-actions"><button onClick={()=>updateLocker(x)}>Capacidade</button><button onClick={()=>condition(x)}>Condição</button></div></td></tr>)}</tbody></table></div><h3>Novo armário</h3><form className="form-grid" onSubmit={createLocker}><label>Local<select required value={locker.locationId} onChange={e=>setLocker({...locker,locationId:e.target.value})}><option value="">Selecione</option>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Número<input required value={locker.number} onChange={e=>setLocker({...locker,number:e.target.value})}/></label><label>Porte<select value={locker.size} onChange={e=>setLocker({...locker,size:e.target.value})}><option value="padrao">Padrão</option><option value="grande">Grande</option></select></label><label>Limite máximo<input type="number" min={1} value={locker.capacity} onChange={e=>setLocker({...locker,capacity:Number(e.target.value)})}/></label><label>Modalidade<select value={locker.modality} onChange={e=>setLocker({...locker,modality:e.target.value})}><option value="fixo">Fixo</option><option value="rotativo">Rotativo</option></select></label><label>Destinação<input value={locker.destination} onChange={e=>setLocker({...locker,destination:e.target.value})}/></label><button className="primary">Cadastrar armário</button></form></section>
      <section className="card"><h2>Acessos</h2><div className="list">{users.map(x=><div className="list-row" key={x.id}><div><strong>{x.email}</strong><small>{x.role} · {x.active?'ativo':'inativo'}{x.must_change_password?' · troca de senha pendente':''}</small></div><div className="row-actions"><button onClick={()=>changeRole(x)}>Perfil</button><button onClick={()=>toggleUser(x)}>{x.active?'Desativar':'Ativar'}</button><button onClick={()=>reset(x)}>Redefinir senha</button></div></div>)}</div><h3>Novo usuário</h3><form className="form-grid" onSubmit={createUser}><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Perfil<select value={role} onChange={e=>setRole(e.target.value)}><option value="filial_admin">Administrador da filial</option><option value="operador">Operador</option><option value="consulta">Consulta</option></select></label><label>Senha temporária<input type="password" minLength={12} required value={temporaryPassword} onChange={e=>setTemporaryPassword(e.target.value)}/></label><button className="primary">Criar usuário</button></form></section>
      <section className="card"><h2>Consulta offline</h2><p>Autorize este navegador no PC da supervisão. A cópia é somente de leitura e expira após 24 horas.</p><form className="inline-form" onSubmit={device}><label>Identificação do dispositivo<input value={deviceLabel} onChange={e=>setDeviceLabel(e.target.value)}/></label><button>Autorizar este navegador</button></form><div className="list">{devices.map(item=><div className="list-row" key={item.id}><div><strong>{item.label}</strong><small>{item.revoked_at?'Revogado':'Autorizado'} · {new Date(item.created_at).toLocaleDateString('pt-BR')}</small></div>{!item.revoked_at&&<button onClick={()=>revokeDevice(item)}>Revogar</button>}</div>)}</div></section>
    </>}</div>;
}
