import {useEffect,useState} from 'react';
import {api,op,post,patch} from '../api';
import {saveDevice} from '../offline';
import type {PageProps} from '../App';
type Locker={id:string;number:string;sector_occupant:string|null;size:string;capacity:number;is_double:boolean;condition:string;modality:string;destination:string|null;version:number;occupants:unknown[];migration_status:string};
type User={id:string;username:string;role:string;active:boolean;must_change_password:boolean;version:number};
type Device={id:string;label:string;revoked_at:string|null;version:number;created_at:string};
export function Admin({branchId,readonly,refresh,notice,general=false}:PageProps&{general?:boolean}){
  const [lockers,setLockers]=useState<Locker[]>([]),[users,setUsers]=useState<User[]>([]),[devices,setDevices]=useState<Device[]>([]);
  const [branchName,setBranchName]=useState(''),[timezone,setTimezone]=useState('America/Fortaleza');
  const [locker,setLocker]=useState({number:'',size:'padrao',capacity:1,isDouble:false,modality:'fixo',destination:'',sectorOccupant:'',condition:'disponivel'});
  const [username,setUsername]=useState(''),[role,setRole]=useState('operador'),[temporaryPassword,setTemporaryPassword]=useState(''),[deviceLabel,setDeviceLabel]=useState('PC da supervisão');
  async function load(){if(!branchId)return;const [b,c,d]=await Promise.all([api<Locker[]>(`/branches/${branchId}/lockers`),api<User[]>(`/branches/${branchId}/users`),api<Device[]>(`/branches/${branchId}/devices`)]);setLockers(b);setUsers(c);setDevices(d);}
  useEffect(()=>{if(!readonly)load().catch(e=>notice(e.message));},[branchId,readonly]);
  async function act(fn:()=>Promise<unknown>){try{await fn();await load();refresh();notice('Alteração registrada.');}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  async function createBranch(event:React.FormEvent){event.preventDefault();try{await post('/branches',{operationId:op(),name:branchName,timezone});window.location.reload();}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  async function createLocker(event:React.FormEvent){event.preventDefault();await act(()=>post(`/branches/${branchId}/lockers`,{operationId:op(),...locker,destination:locker.destination||null,sectorOccupant:locker.sectorOccupant||null}));setLocker({...locker,number:'',destination:'',sectorOccupant:''});}
  async function createUser(event:React.FormEvent){event.preventDefault();await act(()=>post(`/branches/${branchId}/users`,{operationId:op(),username,role,temporaryPassword}));setUsername('');setTemporaryPassword('');}
  async function reset(user:User){const password=window.prompt(`Nova senha temporária para ${user.username} (12 caracteres ou mais):`);if(!password)return;await act(()=>post(`/branches/${branchId}/users/${user.id}/reset`,{operationId:op(),expectedVersion:user.version,temporaryPassword:password}));}
  async function toggleUser(user:User){if(!window.confirm(`${user.active?'Desativar':'Ativar'} ${user.username}?`))return;await act(()=>patch(`/branches/${branchId}/users/${user.id}`,{operationId:op(),expectedVersion:user.version,active:!user.active}));}
  async function changeRole(user:User){const next=window.prompt('Perfil: filial_admin, operador ou consulta',user.role);if(!next||next===user.role)return;await act(()=>patch(`/branches/${branchId}/users/${user.id}`,{operationId:op(),expectedVersion:user.version,role:next}));}
  async function toggleDouble(item:Locker){await act(()=>patch(`/branches/${branchId}/lockers/${item.id}`,{operationId:op(),expectedVersion:item.version,isDouble:!item.is_double,capacity:item.is_double?1:2}));}
  async function sector(item:Locker){const value=window.prompt(`Setor que ocupa o armário ${item.number} (deixe vazio para liberar):`,item.sector_occupant??'');if(value===null)return;await act(()=>patch(`/branches/${branchId}/lockers/${item.id}`,{operationId:op(),expectedVersion:item.version,sectorOccupant:value.trim()||null}));}
  async function condition(item:Locker){const value=window.prompt('Condição: disponivel, manutencao ou bloqueado',item.condition);if(!value)return;await act(()=>patch(`/branches/${branchId}/lockers/${item.id}`,{operationId:op(),expectedVersion:item.version,condition:value}));}
  async function device(event:React.FormEvent){event.preventDefault();try{const result=await post<{secret:string;id:string}>(`/branches/${branchId}/devices`,{operationId:op(),label:deviceLabel});await saveDevice(result.secret);await load();refresh();notice('Este navegador foi autorizado para consulta offline. A cópia será atualizada.');}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  async function revokeDevice(item:Device){if(!window.confirm(`Revogar ${item.label}? A consulta offline será apagada ao reconectar.`))return;await act(()=>post(`/branches/${branchId}/devices/${item.id}/revoke`,{operationId:op(),expectedVersion:item.version}));}
  return <div className="stack">{general&&<section className="card"><h2>Criar filial</h2><form className="inline-form" onSubmit={createBranch}><label>Nome<input required value={branchName} onChange={e=>setBranchName(e.target.value)}/></label><label>Fuso<input required value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><button className="primary">Criar filial</button></form></section>}
    {!branchId?null:readonly?<section className="card"><p>Administração indisponível neste perfil ou em modo offline.</p></section>:<>
      <section className="card"><h2>Armários</h2><div className="table-wrap"><table><thead><tr><th>Número</th><th>Tipo</th><th>Ocupação</th><th>Condição</th><th>Ações</th></tr></thead><tbody>{lockers.map(x=><tr key={x.id}><td>{x.number}</td><td>{x.is_double?'Duplo':'—'}</td><td>{x.sector_occupant?`Setor: ${x.sector_occupant}`:x.occupants.length?`${x.occupants.length} pessoa(s)`:'Livre'}</td><td>{x.condition}{x.migration_status==='inconclusivo'?' · revisão':''}</td><td><div className="row-actions"><button onClick={()=>toggleDouble(x)}>{x.is_double?'Marcar simples':'Marcar duplo'}</button><button onClick={()=>condition(x)}>Condição</button><button onClick={()=>sector(x)}>Setor ocupante</button></div></td></tr>)}</tbody></table></div><h3>Novo armário</h3><form className="form-grid" onSubmit={createLocker}><label>Número<input required value={locker.number} onChange={e=>setLocker({...locker,number:e.target.value})}/></label><label className="check"><input type="checkbox" checked={locker.isDouble} onChange={e=>setLocker({...locker,isDouble:e.target.checked,capacity:e.target.checked?2:1})}/>Armário duplo (dois compartimentos)</label><label>Modalidade<select value={locker.modality} onChange={e=>setLocker({...locker,modality:e.target.value})}><option value="fixo">Fixo</option><option value="rotativo">Rotativo</option></select></label><label>Destinação<input value={locker.destination} onChange={e=>setLocker({...locker,destination:e.target.value})}/></label><label>Setor ocupante (opcional)<input value={locker.sectorOccupant} onChange={e=>setLocker({...locker,sectorOccupant:e.target.value})} placeholder="Ex.: Jerinana"/></label><button className="primary">Cadastrar armário</button></form></section>
      <section className="card"><h2>Acessos</h2><div className="list">{users.map(x=><div className="list-row" key={x.id}><div><strong>{x.username}</strong><small>{x.role} · {x.active?'ativo':'inativo'}{x.must_change_password?' · troca de senha pendente':''}</small></div><div className="row-actions"><button onClick={()=>changeRole(x)}>Perfil</button><button onClick={()=>toggleUser(x)}>{x.active?'Desativar':'Ativar'}</button><button onClick={()=>reset(x)}>Redefinir senha</button></div></div>)}</div><h3>Novo usuário</h3><form className="form-grid" onSubmit={createUser}><label>Nome de usuário<input required minLength={3} pattern="[a-zA-Z0-9._-]+" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Perfil<select value={role} onChange={e=>setRole(e.target.value)}><option value="filial_admin">Administrador da filial</option><option value="operador">Operador</option><option value="consulta">Consulta</option></select></label><label>Senha temporária<input type="password" minLength={12} required value={temporaryPassword} onChange={e=>setTemporaryPassword(e.target.value)}/></label><button className="primary">Criar usuário</button></form></section>
      <section className="card"><h2>Consulta offline</h2><p>Autorize este navegador no PC da supervisão. A cópia é somente de leitura e expira após 24 horas.</p><form className="inline-form" onSubmit={device}><label>Identificação do dispositivo<input value={deviceLabel} onChange={e=>setDeviceLabel(e.target.value)}/></label><button>Autorizar este navegador</button></form><div className="list">{devices.map(item=><div className="list-row" key={item.id}><div><strong>{item.label}</strong><small>{item.revoked_at?'Revogado':'Autorizado'} · {new Date(item.created_at).toLocaleDateString('pt-BR')}</small></div>{!item.revoked_at&&<button onClick={()=>revokeDevice(item)}>Revogar</button>}</div>)}</div></section>
    </>}</div>;
}
