import {useEffect,useMemo,useState} from 'react';
import {api,op,post} from '../api';
import type {PageProps} from '../App';

type Occupant={allocationId:string;allocationVersion:number;personId:string;name:string;registration:string|null;dueAt:string|null};
type Locker={id:string;number:string;location_name:string;size:string;capacity:number;modality:string;destination:string|null;condition:string;migration_status:string;version:number;occupants:Occupant[]};
type Person={person_id:string;name:string;registration:string|null;category:string;status:string;locker_id:string|null};
type Stats={lockers:{total:string;occupied:string;blocked:string};people:{total:string};pending:{total:string}};
export function Dashboard({branchId,readonly,copy,refresh,notice}:PageProps){
  const [lockers,setLockers]=useState<Locker[]>([]),[people,setPeople]=useState<Person[]>([]),[stats,setStats]=useState<Stats|null>(null);
  const [query,setQuery]=useState(''),[location,setLocation]=useState(''),[condition,setCondition]=useState(''),[selected,setSelected]=useState<string|null>(null);
  const [personId,setPersonId]=useState(''),[dueAt,setDueAt]=useState(''),[seasonal,setSeasonal]=useState(false),[reason,setReason]=useState(''),[note,setNote]=useState(''),[sharingReason,setSharingReason]=useState(''),[sharingDue,setSharingDue]=useState(''),[transferId,setTransferId]=useState('');
  const [busy,setBusy]=useState(false);
  async function load(){if(copy){setLockers(copy.lockers as Locker[]);setPeople(copy.people as Person[]);setStats(null);return;}
    const [l,p,s]=await Promise.all([api<Locker[]>(`/branches/${branchId}/lockers`),api<Person[]>(`/branches/${branchId}/people`),api<Stats>(`/branches/${branchId}/dashboard`)]);setLockers(l);setPeople(p);setStats(s);
  }
  useEffect(()=>{load().catch(e=>notice(e.message));},[branchId,copy]);
  const locations=[...new Set(lockers.map(x=>x.location_name))].sort();
  const filtered=useMemo(()=>lockers.filter(x=>(!location||x.location_name===location)&&(!condition||x.condition===condition)&&(!query||[x.number,x.location_name,...x.occupants.map(o=>o.name),...x.occupants.map(o=>o.registration??'')].some(v=>v.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))))),[lockers,query,location,condition]);
  const locker=lockers.find(x=>x.id===selected);
  async function act(fn:()=>Promise<unknown>){setBusy(true);try{await fn();notice('Movimentação registrada.');await load();refresh();setPersonId('');setNote('');setReason('');setSharingReason('');setSharingDue('');setTransferId('');}catch(e){notice(e instanceof Error?e.message:'Falha na operação');}finally{setBusy(false);}}
  function occupy(event:React.FormEvent){event.preventDefault();if(!locker)return;act(()=>post(`/branches/${branchId}/allocations/occupy`,{operationId:op(),personId,lockerId:locker.id,expectedVersion:locker.version,modality:locker.modality,seasonal,dueAt:dueAt?new Date(`${dueAt}T12:00:00`).toISOString():null,reason,note,sharingReason,sharingDueAt:sharingDue?new Date(`${sharingDue}T12:00:00`).toISOString():null}));}
  function release(occupant:Occupant){if(!locker||!window.confirm(`Liberar ${occupant.name} do armário ${locker.location_name} ${locker.number}?`))return;act(()=>post(`/branches/${branchId}/allocations/release`,{operationId:op(),allocationId:occupant.allocationId,expectedVersion:occupant.allocationVersion,note}));}
  function transfer(occupant:Occupant){if(!locker||!transferId)return;const destination=lockers.find(x=>x.id===transferId);if(!destination)return;if(!window.confirm(`Transferir ${occupant.name} de ${locker.location_name} ${locker.number} para ${destination.location_name} ${destination.number}?`))return;act(()=>post(`/branches/${branchId}/allocations/transfer`,{operationId:op(),allocationId:occupant.allocationId,expectedAllocationVersion:occupant.allocationVersion,destinationLockerId:destination.id,sourceVersion:locker.version,destinationVersion:destination.version,note,sharingReason,sharingDueAt:sharingDue?new Date(`${sharingDue}T12:00:00`).toISOString():null}));}
  return <>
    <section className="stats" aria-label="Indicadores"><div className="stat"><small>Armários físicos</small><strong>{stats?.lockers.total??lockers.length}</strong></div><div className="stat"><small>Ocupados</small><strong>{stats?.lockers.occupied??lockers.filter(x=>x.occupants?.length).length}</strong></div><div className="stat"><small>Bloqueados / revisão</small><strong>{stats?.lockers.blocked??lockers.filter(x=>x.condition!=='disponivel'||x.migration_status==='inconclusivo').length}</strong></div><div className="stat"><small>Pendências</small><strong>{stats?.pending.total??copy?.pending.length??'—'}</strong></div></section>
    <section className="card"><div className="section-head"><div><h2>Armários</h2><p>{filtered.length} resultados · armário grande ocupado não é contado como livre</p></div></div><div className="filters"><label>Buscar por nome, matrícula ou armário<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Digite para buscar"/></label><label>Local<select value={location} onChange={e=>setLocation(e.target.value)}><option value="">Todos</option>{locations.map(x=><option key={x}>{x}</option>)}</select></label><label>Condição<select value={condition} onChange={e=>setCondition(e.target.value)}><option value="">Todas</option><option value="disponivel">Disponível</option><option value="manutencao">Manutenção</option><option value="bloqueado">Bloqueado</option></select></label></div>
      <div className="locker-grid">{filtered.map(x=><button key={x.id} className={`locker-tile ${x.occupants?.length?'occupied':''} ${selected===x.id?'selected':''}`} onClick={()=>setSelected(x.id)} aria-pressed={selected===x.id}><span className="tile-top"><strong>{x.number}</strong><span className="badge">{x.occupants?.length?`${x.occupants.length} ocupante${x.occupants.length>1?'s':''}`:x.condition==='disponivel'&&x.migration_status==='conferido'?'Livre':'Indisponível'}</span></span><small>{x.location_name} · {x.size==='grande'?'Grande':'Padrão'}</small><span>{x.occupants?.map(o=>o.name).join(', ')||x.destination||'Sem ocupante'}</span></button>)}</div>
    </section>
    {locker&&<section className="card detail"><div className="section-head"><div><h2>{locker.location_name} · Armário {locker.number}</h2><p>{locker.size==='grande'?'Grande':'Padrão'} · {locker.modality==='rotativo'?'Rotativo':'Fixo'} · capacidade {locker.capacity} · {locker.condition}</p></div><button onClick={()=>setSelected(null)}>Fechar</button></div>
      {locker.destination&&<p>Destinação: {locker.destination}</p>}{locker.migration_status==='inconclusivo'&&<p className="warning">Migração inconclusiva: novas entradas bloqueadas.</p>}
      <h3>Ocupantes</h3>{locker.occupants?.length?<div className="list">{locker.occupants.map(o=><div className="list-row" key={o.allocationId}><div><strong>{o.name}</strong><small>{o.registration??'Sem matrícula'}{o.dueAt?` · previsão ${new Date(o.dueAt).toLocaleDateString('pt-BR')}`:''}</small></div>{!readonly&&<div className="row-actions"><button disabled={busy} onClick={()=>release(o)}>Registrar saída</button><select aria-label={`Destino para ${o.name}`} value={transferId} onChange={e=>setTransferId(e.target.value)}><option value="">Destino</option>{lockers.filter(l=>l.id!==locker.id&&l.modality===locker.modality&&l.condition==='disponivel'&&l.migration_status==='conferido'&&l.occupants.length<l.capacity).map(l=><option key={l.id} value={l.id}>{l.location_name} · {l.number}</option>)}</select><button disabled={busy||!transferId} onClick={()=>transfer(o)}>Transferir</button></div>}</div>)}</div>:<p className="muted">Nenhuma ocupação ativa.</p>}
      {!readonly&&locker.condition==='disponivel'&&locker.migration_status==='conferido'&&locker.occupants.length<locker.capacity&&<form className="form-grid" onSubmit={occupy}><h3>Registrar entrada</h3><label>Pessoa<select required value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Selecione</option>{people.filter(p=>p.status==='ativo'&&!p.locker_id).map(p=><option key={p.person_id} value={p.person_id}>{p.name} · {p.registration??'sem matrícula'}</option>)}</select></label><label>Motivo<input value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Observação<input value={note} onChange={e=>setNote(e.target.value)}/></label><label className="check"><input type="checkbox" checked={seasonal} onChange={e=>setSeasonal(e.target.checked)}/> Alocação sazonal</label>{seasonal&&<label>Previsão de saída<input type="date" required value={dueAt} onChange={e=>setDueAt(e.target.value)}/><span className="quick"><button type="button" onClick={()=>setDueAt(new Date(Date.now()+45*86400000).toISOString().slice(0,10))}>45 dias</button><button type="button" onClick={()=>setDueAt(new Date(Date.now()+90*86400000).toISOString().slice(0,10))}>90 dias</button></span></label>}{locker.occupants.length>0&&<><label>Motivo do compartilhamento<input required value={sharingReason} onChange={e=>setSharingReason(e.target.value)}/></label><label>Previsão de encerramento<input type="date" required value={sharingDue} onChange={e=>setSharingDue(e.target.value)}/></label></>}<button className="primary" disabled={busy}>Confirmar entrada em {locker.location_name} · {locker.number}</button></form>}
    </section>}
  </>;
}
