import {useState} from 'react';
import {api,op,post} from '../api';
import type {PageProps} from '../App';

type Sheet={name:string;preview:string[][];rows:number};
type Change={row:{row:number;registration:string;name:string;department:string|null;functionName:string|null};before:{name:string;department:string|null;function_name:string|null}};
type Conflict={row:number;registration:string;existing:{name:string;category:string;origin:string}};
type Preview={importId:string;baseRevision:string;extractedOn:string;counts:{previous:number;current:number;absent:number};inclusions:{row:number;registration:string;name:string}[];changes:Change[];absences:{id:string;registration:string;name:string}[];unchanged:unknown[];conflicts:Conflict[]};
type FormulaIssue={key:string;row:number;number:string;column:string;source:string;suggestion:string|null;uniqueBanco:boolean};
type MigrationPreview={importId:string;physicalCount:number;sourceRows:number;duplicateNumbers:string[];duplicateRegistrations:string[];largeCount:number;uncertainRows:{row:number;number:string;name:string;registration:string;suggestedCategory:string}[];categorySuggestions:{row:number;number:string;name:string;registration:string;suggestedCategory:string}[];sourceProposals:{row:number;number:string;name:string;registration:string;department:string;functionName:string;status:string;size:string;proposedCapacity:number;observation:string;address:string;modified:string;suggestedCategory:string;uncertain:boolean}[];formulaIssues:FormulaIssue[];legacyHistoryRows:number};
export function Imports({branchId,readonly,refresh,notice}:PageProps){
  const [file,setFile]=useState<File|null>(null),[sheets,setSheets]=useState<Sheet[]>([]),[sheet,setSheet]=useState(''),[headerRow,setHeaderRow]=useState(1),[mapping,setMapping]=useState({registration:'MATRÍCULA',name:'NOME',department:'SETOR',functionName:'FUNÇÃO'});
  const [encoding,setEncoding]=useState('utf8'),[delimiter,setDelimiter]=useState(''),[extractedOn,setExtractedOn]=useState(new Date().toISOString().slice(0,10)),[preview,setPreview]=useState<Preview|null>(null);
  const [complete,setComplete]=useState(false),[sameDate,setSameDate]=useState(false),[resolved,setResolved]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false);
  const [migration,setMigration]=useState<MigrationPreview|null>(null),[locations,setLocations]=useState<{id:string;name:string}[]>([]),[migrationLocation,setMigrationLocation]=useState(''),[capacitiesConfirmed,setCapacitiesConfirmed]=useState(false),[categoriesConfirmed,setCategoriesConfirmed]=useState(false),[acceptBanco,setAcceptBanco]=useState(false),[formulaOverrides,setFormulaOverrides]=useState<Record<string,string>>({}),[duplicateDecisions,setDuplicateDecisions]=useState<Record<string,string>>({}),[categoryOverrides,setCategoryOverrides]=useState<Record<string,string>>({}),[capacityOverrides,setCapacityOverrides]=useState<Record<string,number>>({});
  async function inspect(){if(!file)return;setBusy(true);try{const data=new FormData();data.append('encoding',encoding);data.append('delimiter',delimiter);data.append('file',file);const result=await api<{sheets:Sheet[]}>(`/branches/${branchId}/imports/inspect`,{method:'POST',body:data});setSheets(result.sheets);setSheet(result.sheets.find(x=>x.name==='COLABORADORES')?.name??result.sheets[0]?.name??'');setPreview(null);}catch(e){notice(e instanceof Error?e.message:'Falha na inspeção');}finally{setBusy(false);}}
  async function prepare(){if(!file)return;setBusy(true);try{const data=new FormData();data.append('operationId',op());data.append('sheet',sheet);data.append('headerRow',String(headerRow));data.append('extractedOn',extractedOn);data.append('mapping',JSON.stringify({registration:mapping.registration,name:mapping.name,department:mapping.department||undefined,functionName:mapping.functionName||undefined}));data.append('encoding',encoding);data.append('delimiter',delimiter);data.append('file',file);setPreview(await api<Preview>(`/branches/${branchId}/imports/ti/prepare`,{method:'POST',body:data}));setComplete(false);setResolved({});}catch(e){notice(e instanceof Error?e.message:'Falha na prévia');}finally{setBusy(false);}}
  async function confirm(){if(!preview)return;setBusy(true);try{const resolutions=Object.fromEntries(preview.conflicts.filter(x=>resolved[x.registration]).map(x=>[x.registration,'converter_para_ti']));await post(`/branches/${branchId}/imports/${preview.importId}/confirm`,{operationId:op(),acknowledgeComplete:complete,sameDateCorrection:sameDate,resolutions});notice('Base da TI atualizada e pendências recalculadas.');setPreview(null);refresh();}catch(e){notice(e instanceof Error?e.message:'Falha na confirmação');}finally{setBusy(false);}}
  async function prepareMigration(){if(!file)return;setBusy(true);try{const data=new FormData();data.append('operationId',op());data.append('file',file);const [result,local]=await Promise.all([api<MigrationPreview>(`/branches/${branchId}/imports/migration/prepare`,{method:'POST',body:data}),api<{id:string;name:string}[]>(`/branches/${branchId}/locations`)]);setMigration(result);setLocations(local);setMigrationLocation(local[0]?.id??'');}catch(e){notice(e instanceof Error?e.message:'Falha ao preparar migração');}finally{setBusy(false);}}
  async function confirmMigration(){if(!migration)return;setBusy(true);try{await post(`/branches/${branchId}/imports/migration/${migration.importId}/confirm`,{operationId:op(),locationId:migrationLocation,confirmCapacities:capacitiesConfirmed,acceptSuggestedCategories:categoriesConfirmed,acceptBancoSuggestions:acceptBanco,formulaOverrides,duplicateDecisions,categoryOverrides,capacityOverrides});notice('Migração registrada. Armários incertos permanecem bloqueados até conferência.');setMigration(null);refresh();}catch(e){notice(e instanceof Error?e.message:'Falha na migração');}finally{setBusy(false);}}
  const selected=sheets.find(x=>x.name===sheet),headers=selected?.preview[headerRow-1]??[];
  return <><section className="card"><div className="section-head"><div><h2>Atualização da TI</h2><p>Arquivo completo de colaboradores ativos da filial. Cadastros manuais são preservados.</p></div></div>{readonly?<p>Importação indisponível para este perfil ou em modo offline.</p>:<div className="form-grid"><label>Arquivo XLSX ou CSV (até 10 MB)<input type="file" accept=".xlsx,.csv" onChange={e=>{setFile(e.target.files?.[0]??null);setSheets([]);setPreview(null);}}/></label><label>Data da extração<input type="date" value={extractedOn} onChange={e=>setExtractedOn(e.target.value)}/></label><label>Codificação CSV<select value={encoding} onChange={e=>setEncoding(e.target.value)}><option value="utf8">UTF-8</option><option value="win1252">Windows-1252</option><option value="latin1">Latin-1</option></select></label><label>Delimitador CSV<select value={delimiter} onChange={e=>setDelimiter(e.target.value)}><option value="">Detectar</option><option value=",">Vírgula</option><option value=";">Ponto e vírgula</option></select></label><button disabled={!file||busy} onClick={inspect}>Inspecionar arquivo</button></div>}</section>
    {selected&&<section className="card"><div className="section-head"><div><h2>Mapeamento e amostra</h2><p>Confira os cabeçalhos antes de comparar.</p></div></div><div className="form-grid"><label>Aba<select value={sheet} onChange={e=>setSheet(e.target.value)}>{sheets.map(x=><option key={x.name}>{x.name}</option>)}</select></label><label>Linha do cabeçalho<input type="number" min={1} value={headerRow} onChange={e=>setHeaderRow(Number(e.target.value))}/></label>{(['registration','name','department','functionName'] as const).map(key=><label key={key}>{({registration:'Matrícula',name:'Nome',department:'Setor (opcional)',functionName:'Função (opcional)'})[key]}<select value={mapping[key]} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">Não informado</option>{headers.map((h,i)=><option key={i} value={h}>{h}</option>)}</select></label>)}<button className="primary" disabled={busy} onClick={prepare}>Comparar com base atual</button></div><div className="table-wrap"><table><tbody>{selected.preview.map((row,i)=><tr key={i}><th>{i+1}</th>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div></section>}
    {preview&&<section className="card"><div className="section-head"><div><h2>Prévia do lote</h2><p>Revisão comparada: {preview.baseRevision} · extração {new Date(`${preview.extractedOn}T12:00:00`).toLocaleDateString('pt-BR')}</p></div></div><div className="stats compact"><div className="stat"><small>Base anterior</small><strong>{preview.counts.previous}</strong></div><div className="stat"><small>Arquivo atual</small><strong>{preview.counts.current}</strong></div><div className="stat"><small>Ausentes</small><strong>{preview.counts.absent}</strong></div></div><div className="diff-grid"><Diff title="Inclusões" rows={preview.inclusions.map(x=>`${x.registration} · ${x.name}`)}/><Diff title="Alterações" rows={preview.changes.map(describeChange)}/><Diff title="Ausências" rows={preview.absences.map(x=>`${x.registration} · ${x.name}`)}/><Diff title="Inalterados" rows={[]} count={preview.unchanged.length}/></div>
      {preview.conflicts.length>0&&<div className="warning"><h3>Conflitos de identidade</h3><p>Converter um cadastro manual para colaborador da TI preserva a pessoa e o histórico. Confirme cada vínculo.</p>{preview.conflicts.map(c=><label className="check" key={c.registration}><input type="checkbox" checked={!!resolved[c.registration]} onChange={e=>setResolved({...resolved,[c.registration]:e.target.checked})}/> Matrícula {c.registration}: {c.existing.name} ({c.existing.category}) → registro da TI, linha {c.row}</label>)}</div>}
      <label className="check"><input type="checkbox" checked={complete} onChange={e=>setComplete(e.target.checked)}/> Confirmo que este arquivo contém a lista completa de colaboradores ativos da filial e revisei as {preview.counts.absent} ausências.</label><label className="check"><input type="checkbox" checked={sameDate} onChange={e=>setSameDate(e.target.checked)}/> Este arquivo corrige uma extração já aplicada na mesma data (se necessário).</label><button className="primary" disabled={busy||!complete||preview.conflicts.some(c=>!resolved[c.registration])} onClick={confirm}>Confirmar atualização integral</button></section>}
    {!readonly&&<section className="card"><h2>Migração inicial dos armários</h2><p>Usa a aba ARMÁRIOS da planilha legada. Os dados da aba HISTÓRICO são preservados à parte. O início original de cada ocupação permanece desconhecido.</p><button disabled={!file||busy} onClick={prepareMigration}>Preparar migração do arquivo selecionado</button></section>}
    {migration&&<section className="card"><div className="section-head"><div><h2>Revisão da migração</h2><p>{migration.sourceRows} {migration.sourceRows===1?'linha':'linhas'} de origem → {migration.physicalCount} {migration.physicalCount===1?'armário físico':'armários físicos'} · {migration.largeCount} grandes · {migration.legacyHistoryRows} linhas de histórico legado</p></div></div><label>Local dos armários<select value={migrationLocation} onChange={e=>setMigrationLocation(e.target.value)}><option value="">Selecione</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{!locations.length&&<p className="warning">Cadastre o local em Administração antes de confirmar.</p>}
      <div className="warning"><h3>Números duplicados</h3>{migration.duplicateNumbers.length?migration.duplicateNumbers.map(number=><label key={number}>Armário {number}<select value={duplicateDecisions[number]??''} onChange={e=>setDuplicateDecisions({...duplicateDecisions,[number]:e.target.value})}><option value="">Revisão obrigatória</option><option value="same_physical">Mesmo armário físico; manter bloqueado para conferência</option><option value="mark_inconclusive">Identificação inconclusiva; manter bloqueado</option></select></label>):<p>Nenhuma duplicidade.</p>}</div>
      {migration.duplicateRegistrations.length>0&&<p className="warning">Matrículas duplicadas: {migration.duplicateRegistrations.join(', ')}. Corrija o arquivo antes de confirmar.</p>}
      {migration.formulaIssues.length>0&&<div className="warning"><h3>Fórmulas sem resultado: {migration.formulaIssues.length}</h3><p>O arquivo não contém o valor calculado destas células. A aba BANCO DE DADOS é usada apenas como sugestão para revisão explícita.</p><label className="check"><input type="checkbox" checked={acceptBanco} onChange={e=>setAcceptBanco(e.target.checked)}/> Confirmo o uso das {migration.formulaIssues.filter(x=>x.uniqueBanco).length} sugestões com correspondência única no BANCO DE DADOS, inclusive células vazias.</label>{migration.formulaIssues.filter(x=>!x.uniqueBanco).map(issue=><label key={issue.key}>Linha {issue.row}, coluna {issue.column}, armário {issue.number} ({issue.source}) — valor conferido<input value={formulaOverrides[issue.key]??''} onChange={e=>setFormulaOverrides({...formulaOverrides,[issue.key]:e.target.value})} placeholder="Digite o valor; vazio exige marcação abaixo"/></label>)}{migration.formulaIssues.filter(x=>!x.uniqueBanco).map(issue=><label className="check" key={`${issue.key}-blank`}><input type="checkbox" checked={Object.hasOwn(formulaOverrides,issue.key)&&formulaOverrides[issue.key]===''} onChange={e=>{const next={...formulaOverrides};if(e.target.checked)next[issue.key]='';else delete next[issue.key];setFormulaOverrides(next);}}/> Confirmo célula vazia na linha {issue.row}, coluna {issue.column}</label>)}</div>}
      <label className="check"><input type="checkbox" checked={capacitiesConfirmed} onChange={e=>setCapacitiesConfirmed(e.target.checked)}/> Revisei a sugestão de capacidade: padrão 1, grande 2. A capacidade pode ser ajustada abaixo por número.</label><label className="check"><input type="checkbox" checked={categoriesConfirmed} onChange={e=>setCategoriesConfirmed(e.target.checked)}/> Revisei e confirmo as categorias sugeridas; as alterações específicas estão abaixo.</label>
      <details><summary>Revisar {migration.sourceProposals.length} {migration.sourceProposals.length===1?'linha':'linhas'} de origem, categorias e capacidades</summary><p>Capacidade é por armário físico. MODIFICADO é dado da origem e não define o início da ocupação.</p><div className="table-wrap"><table><thead><tr><th>Linha</th><th>Armário</th><th>Status de origem</th><th>Pessoa / matrícula</th><th>Setor / função</th><th>Categoria proposta</th><th>Porte</th><th>Capacidade</th><th>Observação / endereço</th><th>MODIFICADO</th><th>Conferência</th></tr></thead><tbody>{migration.sourceProposals.map(row=><tr key={row.row}><td>{row.row}</td><td>{row.number}</td><td>{row.status}</td><td>{row.name||'—'}<small>{row.registration||'Sem matrícula'}</small></td><td>{row.department||'—'}<small>{row.functionName||'—'}</small></td><td>{row.name?<select value={categoryOverrides[String(row.row)]??row.suggestedCategory} onChange={e=>setCategoryOverrides({...categoryOverrides,[String(row.row)]:e.target.value})}><option value="colaborador">Colaborador</option><option value="promotor_fixo">Promotor fixo</option><option value="roteirista">Roteirista</option><option value="terceirizado">Terceirizado</option></select>:'—'}</td><td>{row.size==='grande'?'Grande':'Padrão'}</td><td><input type="number" min={1} aria-label={`Capacidade do armário ${row.number}`} value={capacityOverrides[row.number]??row.proposedCapacity} onChange={e=>setCapacityOverrides({...capacityOverrides,[row.number]:Number(e.target.value)})}/></td><td>{row.observation||'—'}<small>{row.address||'—'}</small></td><td>{row.modified||'—'}</td><td>{row.uncertain?'Pendente':'Sem divergência identificada'}</td></tr>)}</tbody></table></div></details>
      <p className="warning">{migration.uncertainRows.length} linhas exigirão conferência. Armários com identificação ou ocupação incerta ficarão bloqueados para novas entradas.</p><button className="primary" disabled={busy||!migrationLocation||!capacitiesConfirmed||!categoriesConfirmed||migration.duplicateRegistrations.length>0||migration.duplicateNumbers.some(n=>!duplicateDecisions[n])||migration.formulaIssues.some(x=>!Object.hasOwn(formulaOverrides,x.key)&&!(acceptBanco&&x.uniqueBanco))} onClick={confirmMigration}>Confirmar migração com pendências</button></section>}
  </>;
}
function describeChange(change:Change){const fields:string[]=[];if(change.before.name!==change.row.name)fields.push(`nome: ${change.before.name} → ${change.row.name}`);if(change.before.department!==change.row.department)fields.push(`setor: ${change.before.department??'—'} → ${change.row.department??'—'}`);if(change.before.function_name!==change.row.functionName)fields.push(`função: ${change.before.function_name??'—'} → ${change.row.functionName??'—'}`);return `${change.row.registration} · ${fields.join('; ')}`;}
function Diff({title,rows,count=rows.length}:{title:string;rows:string[];count?:number}){return <div className="diff-card"><h3>{title} <span className="count">{count}</span></h3><div className="diff-list">{rows.length?rows.slice(0,30).map((x,i)=><p key={i}>{x}</p>):<p>{count?`${count} registros`:'Nenhum registro'}</p>}{rows.length>30&&<p>… e mais {rows.length-30}</p>}</div></div>;}
