import {useEffect,useState} from 'react';
import {api,op,post,patch} from '../api';
import type {PageProps} from '../App';

type Person={id:string;person_id:string;name:string;registration:string|null;category:string;origin:string;company:string|null;department:string|null;function_name:string|null;status:string;needs_fixed:boolean;ti_present:boolean|null;version:number;locker_id:string|null;number:string|null;location_name:string|null};
const empty={name:'',registration:'',category:'promotor_fixo',company:'',department:'',functionName:'',needsFixed:true};
export function People({branchId,readonly,copy,refresh,notice}:PageProps){
  const [people,setPeople]=useState<Person[]>([]),[q,setQ]=useState(''),[category,setCategory]=useState(''),[form,setForm]=useState(empty),[editing,setEditing]=useState<Person|null>(null),[busy,setBusy]=useState(false);
  async function load(){if(copy){setPeople(copy.people as Person[]);return;}setPeople(await api<Person[]>(`/branches/${branchId}/people`));}
  useEffect(()=>{load().catch(e=>notice(e.message));},[branchId,copy]);
  const filtered=people.filter(p=>(!category||p.category===category)&&(!q||[p.name,p.registration??'',p.company??'',p.number??''].some(x=>x.toLocaleLowerCase('pt-BR').includes(q.toLocaleLowerCase('pt-BR')))));
  function startEdit(person:Person){setEditing(person);setForm({name:person.name,registration:person.registration??'',category:person.category,company:person.company??'',department:person.department??'',functionName:person.function_name??'',needsFixed:person.needs_fixed});}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);try{
    const payload={...form,registration:form.registration||null,company:form.company||null,department:form.department||null,functionName:form.functionName||null,operationId:op()};
    if(editing)await patch(`/branches/${branchId}/people/${editing.id}`,{...payload,expectedVersion:editing.version});
    else await post(`/branches/${branchId}/people`,{...payload,origin:'manual'});
    setForm(empty);setEditing(null);await load();refresh();notice('Cadastro salvo.');
  }catch(e){notice(e instanceof Error?e.message:'Falha ao salvar');}finally{setBusy(false);}}
  async function status(person:Person){const next=person.status==='ativo'?'encerrado':'ativo';if(!window.confirm(`${next==='encerrado'?'Encerrar atuação':'Reativar'} de ${person.name}? Ocupação atual permanece até liberação explícita.`))return;try{await post(`/branches/${branchId}/people/${person.id}/status`,{operationId:op(),expectedVersion:person.version,status:next});await load();refresh();notice('Situação atualizada.');}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  async function exception(person:Person){const reason=window.prompt(`Motivo da exceção de armário para ${person.name}:`);if(!reason)return;try{await post(`/branches/${branchId}/people/${person.id}/exception`,{operationId:op(),expectedVersion:person.version,reason});await load();refresh();notice('Exceção registrada.');}catch(e){notice(e instanceof Error?e.message:'Falha');}}
  return <><section className="card"><div className="section-head"><div><h2>Pessoas</h2><p>{filtered.length} cadastros encontrados{copy?' · a cópia offline inclui somente ocupantes e pessoas com pendência':''}</p></div></div><div className="filters"><label>Buscar<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, matrícula, empresa ou armário"/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas</option><option value="colaborador">Colaborador</option><option value="promotor_fixo">Promotor fixo</option><option value="roteirista">Roteirista</option><option value="terceirizado">Terceirizado</option></select></label></div><div className="table-wrap"><table><thead><tr><th>Pessoa</th><th>Categoria</th><th>Empresa / setor</th><th>Situação</th><th>Armário</th><th>Ações</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.registration??'Sem matrícula'}</small></td><td>{labelCategory(p.category)}</td><td>{[p.company,p.department].filter(Boolean).join(' · ')||'—'}</td><td>{p.status==='ativo'?'Ativo':'Atuação encerrada'}{p.category==='colaborador'&&p.ti_present===false?<small>Ausente da TI</small>:null}</td><td>{p.number?`${p.location_name} · ${p.number}`:'Sem armário'}</td><td>{!readonly&&<div className="row-actions"><button onClick={()=>startEdit(p)}>Editar</button><button onClick={()=>status(p)}>{p.status==='ativo'?'Encerrar':'Reativar'}</button>{p.needs_fixed&&!p.locker_id&&<button onClick={()=>exception(p)}>Exceção</button>}</div>}</td></tr>)}</tbody></table></div></section>
    {!readonly&&<section className="card"><div className="section-head"><div><h2>{editing?`Editar ${editing.name}`:'Cadastrar pessoa externa'}</h2><p>Promotores fixos usam matrícula emitida pela loja. Roteiristas e terceirizados podem ficar sem matrícula.</p></div>{editing&&<button onClick={()=>{setEditing(null);setForm(empty);}}>Cancelar edição</button>}</div><form className="form-grid" onSubmit={save}><label>Nome<input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value,needsFixed:e.target.value==='promotor_fixo'})}><option value="promotor_fixo">Promotor fixo</option><option value="roteirista">Promotor roteirista</option><option value="terceirizado">Terceirizado</option>{editing?.category==='colaborador'&&<option value="colaborador">Colaborador</option>}</select></label><label>Matrícula<input required={form.category==='promotor_fixo'||form.category==='colaborador'} value={form.registration} onChange={e=>setForm({...form,registration:e.target.value})}/></label><label>Empresa / marca<input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label>Setor<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><label>Função<input value={form.functionName} onChange={e=>setForm({...form,functionName:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.needsFixed} onChange={e=>setForm({...form,needsFixed:e.target.checked})}/> Precisa de armário fixo</label><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar cadastro'}</button></form></section>}
  </>;
}
const labelCategory=(value:string)=>({colaborador:'Colaborador',promotor_fixo:'Promotor fixo',roteirista:'Roteirista',terceirizado:'Terceirizado'} as Record<string,string>)[value]??value;
